"""
models.py — Pydantic schemas for request/response validation.
"""
from __future__ import annotations

from pydantic import BaseModel, Field


class CanvasElement(BaseModel):
    """Single Excalidraw element generated by the AI."""
    type: str = Field(description="Element type")
    x: float = Field(default=100)
    y: float = Field(default=100)
    width: float | None = None
    height: float | None = None
    text: str | None = None
    backgroundColor: str | None = None
    strokeColor: str | None = None
    fontSize: int | None = None
    id: str | None = None
    startId: str | None = None
    endId: str | None = None


class ChatRequest(BaseModel):
    message: str
    session_id: str | None = None


class CanvasContextRequest(BaseModel):
    session_id: str
    elements: list[dict] | None = None
    description: str | None = None


class ClearRequest(BaseModel):
    session_id: str
